### PR TITLE
Remove lodash

### PR DESCRIPTION
**Pull request by DarrenPaulWright**
npm has been giving me warnings about this package for a while because of the dependency on an old version of Lodash. This pull request removes the dependency on Lodash. All the tests pass.

If you don't want to remove Lodash, but just update the dependencies, just accept the first commit.

### CODE REVIEW

**Comment by fvanwijk** [comment]
Thanks! Looks like TravisCI isn't happy yet but I will check in detail when I'm back from honeymoon.
Removing lodash is perfectly fine for me, perhaps even using more ES6+ syntax (eg no Object.assign but spread)?

**Comment by DarrenPaulWright** [comment]
I've now updated to all the latest ES6+ stuff that makes sense to me, and the tests are passing, but there's an error in mochaIstanbul about the spread operator and I'm not sure how to fix it. Perhaps you could take a look at it when you get back.

Enjoy your honeymoon!

**Comment by fvanwijk** [comment]
I looked into it and it seems a lot of effort (for me) to get this old stuff working.
Could you remove the istanbul dependency/config and run `mochaTest` instead when `grunt test` is called?

Later I will remove all legacy dependencies such as Grunt and upgrade the project to a modern simple stack.

**Comment by DarrenPaulWright** [comment]
Done!

**Comment by fvanwijk** [comment]
Awesome. Thanks for your work!

**Pull request merged**
